### ISSUE TITLE
Some files almost entirely highlighted in warning face?

### ISSUE THREAD

**Issue by chriselrod** [ronisbr/julia-ts-mode#6] opened 2023-01-17 18:32 UTC
For example, loading this file:
https://github.com/JuliaSIMD/LoopVectorization.jl/blob/main/src/modeling/graphs.jl
The types in signatures `::Int` appear blue, and everything else is orange.
This is in contrast to files that are highlighted correctly, where the types are still blue, but everything else shows up in a variety of different colors based on my theme (e.g. argument names are white, keywords are red).

I've noticed this in several files (this just happens to be the first with an open source license).

**Comment by ronisbr** [comment] 2023-01-17 19:31
Hi @chriselrod !

I am not able to reproduce this bug. It seems to be working for me:

<img width="2672" alt="Captura de Tela 2023-01-17 às 16 31 18" src="https://user-images.githubusercontent.com/1068295/212994486-b083a6ea-d0d7-4181-ae35-9999e03a2acc.png">

Notice that the font-lock is correct here.

**Comment by chriselrod** [comment] 2023-01-18 11:14
Huh, is that the main branch?
Here is another example that breaks font lock for me:
```julia
function buz(x, y)
    x ? 1 : (;y...)
end
```

**Comment by chriselrod** [comment] 2023-01-18 11:28
Okay, I just updated my julia tree sitter module, and that fixed the problem I just reported (`buz` above is now fine), but `LoopVectorization/src/modeling/graphs.jl` is still broken.

**Comment by chriselrod** [comment] 2023-01-18 11:33
![juliatserror_001](https://user-images.githubusercontent.com/8043603/213160925-14f976e8-3f67-4fb8-82b5-b2bb6e37f329.png)

**Comment by ronisbr** [comment] 2023-01-18 11:40
I really have no idea. I tried changing the font-lock level, but I cannot reproduce this bug. Can you try opening a Julia file and after that opening the problematic one and the same session? I had some strange problems related with some internal behavior of `treesit.el`:

https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-12/msg01932.html

**Comment by ronisbr** [comment] 2023-01-18 11:40
Ah! If you are seeing the `warning` font-lock, it means you are using the level 4. What happens if you change to level 3?

**Comment by chriselrod** [comment] 2023-01-18 11:48
Yes, it goes away if set to 3. I guess I'll stick to the default (3) for now!

**Comment by ronisbr** [comment] 2023-01-18 12:03
Yes, take a look here: https://github.com/tree-sitter/tree-sitter-julia/issues/91

Can you please start to delete parts of the file until you find what is causing the problem and report to upstream?

**Comment by chriselrod** [comment] 2023-01-18 12:24
I did try adding a space on line 11 above, but that didn't fix it, so there is an additional problem.

I can bisect the file later (i.e. deleting half at a time).

**Comment by savq** [comment] 2023-01-19 00:58
I only got an error at [line 1839](https://github.com/JuliaSIMD/LoopVectorization.jl/blob/46d3333b4402d70ee6a4a7d2bf52798e582e148e/src/modeling/graphs.jl#L1839), where it tries to parse the `:for` symbol as a for loop.

I opened a related issue: https://github.com/tree-sitter/tree-sitter-julia/issues/92

**Comment by chriselrod** [comment] 2023-01-21 00:50
The problem came from
```julia
        validreorder[k] == 0x03 || continue# if already demoted, don't need to check again
```
the hash tag immediately after the continue without a space.

**Comment by savq** [comment] 2023-01-22 02:49
Yeah, sorry. I meant besides the comment without a space. That already has an open issue.

**Comment by chriselrod** [comment] 2023-01-23 15:11
Great, and that issue is fixed, leaving only the `:for`.

**Comment by ronisbr** [comment] 2023-09-21 20:41
@chriselrod I think we can close this issue right?

**Closed** 2023-09-21 21:25 UTC
